version: "3.4"
networks:
  dev:
    driver: bridge

services:
  foodie:
    image: docker.io/library/foodie 
    depends_on:
      - "foodie_db"
    container_name: foodie-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=foodie_db;Port=5432;Database=SampleDbFood;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  
  foodie_db:
    image: postgres:latest
    container_name: foodie_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDbFood
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - "app_data:/var/lib/postgresql/data"
    networks:
      - dev
volumes:
  app_data: 
  